networks:
  dev:
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      # -"443:443" для htpps соединения 
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - dev
    depends_on:
      - backend
      - frontend
      
  backend:
    build:
      context: ./backend
    networks:
      - dev

  frontend:
      build:
        context: ./frontend
      networks:
        - dev